global using BallisticTrajectoryCalculator.Forms;
global using BallisticTrajectoryCalculator.Models;
global using BallisticTrajectoryCalculator.Services;
global using BallisticTrajectoryCalculator.ExtencionMethods;
global using System.ComponentModel.DataAnnotations;